name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.13]

    env:
      GH_TOKEN: ${{ secrets.github_token }}
      CSC_LINK: ${{ secrets.CSC_KEY_PASSWORD }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
      WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@master
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@master
        with:
          node-version: 12
      - name: Install Xvfb on Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install xvfb
      - name: Install Node packages
        run: npm ci
      - name: Build Electron App
        run: npm run build
      - name: Integration Tests (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: xvfb-run npm run test
      - name: Integration Tests
        if: startsWith(matrix.os, 'windows') || startsWith(matrix.os, 'macos')
        run: npm run test
      - name: Release Script
        run: npm run release
